# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]
ba="ba" # 7zコマンドの-baオプション

[files]
extend-exclude = ["package-lock.json", "src/frontend/store/project.ts", "*.svg"]
