managePackageManagerVersions: true
minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - esbuild
  - vue-demi

minimumReleaseAgeExclude:
  - "@yamachu/vite-plugin-dotnet-wasm"

packages:
  - web
